# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9080:80/tcp"
      - "9443:443/tcp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    environment:
      - TZ='Pacific/Auckland'
      - WEBPASSWORD=${WEBPASSWORD}
      - HOSTNAME='pihole.nixlan'
      - VIRTUALHOST='pihole.nixlan'
      - DNSMASQ_LISTENING='all'
      - ServerIP=${SERVERIP}
      - WEB_PORT='80'
      - IPv6='false'
    # Volumes store your data between container upgrades
    volumes:
      - './pihole_fs/etc-pihole:/etc/pihole'
      - './pihole_fs/etc-dnsmasq.d:/etc/dnsmasq.d'
      - '/var/log/pihole:/var/log/pihole/'
      - '/etc/hosts:/etc/hosts'  # Host mappings (optional)
      - '/etc/localtime:/etc/localtime:ro'  # Keep system timezone synced
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
      #- NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    # dns important for container updates
    dns: 1.1.1.1
    shm_size: '512mb'
